### ISSUE TITLE
Content inside url() in quotes

### ISSUE THREAD

**Issue by Panya** [declandewet/stylus-conventions#6]
In CSS you can write content of the `url()` without quotes:

``` css
body {
  background: url(some/path/to/image.png);
}
```

But in Stylus everything is expression, so, for example, if you'll write something like this:

``` sass
some = 42

body
  background: url(some/path/to/image.png)
```

This compiles to:

``` css
body {
  background: url("42/path/to/image.png");
}
```

I suggest add a rule that all (not dynamically generated) content inside `url()` should be in quotes:

``` sass
some = 42

body
  background: url("some/path/to/image.png") // or url('some/path/to/image.png')
```
